### ISSUE TITLE
Error: ConnectionError: could not open index file /path/to/dir/reads_R1.fastq.gz.fxi

### ISSUE THREAD

**Issue by SharonLab** [AnantharamanLab/ViWrap#12]
Hello,

I am using this command to run ViWrap:
```
../../ViWrap run \
        --input_metagenome /path/to/dir/assembly.min500.fna \
        --input_reads /path/to/dir/reads_R1.fastq.gz,/path/to/dir/reads_R2.fastq.gz \
        --out_dir ./ViWrap \
        --db_dir /path/to/dir/ViWrap/ViWrap_db \
        --identify_method vs \
        --conda_env_dir /path/to/dir/ViWrap/ViWrap_conda_environments \
        --threads 50 \
        --virome \
        --input_length_limit 2000 \
        --custom_MAGs_dir /path/to/dir/MAGs \
        --iPHoP_db_custom iPHoP_db_custom
```

and I am getting this error:
```
ConnectionError: could not open index file /path/to/dir/reads_R1.fastq.gz.fxi

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../../ViWrap/ViWrap", line 172, in <module>
    output = cli()
  File "../../ViWrap/ViWrap", line 166, in cli
    args["func"](args)
  File "/path/to/dir/ViWrap/scripts/master_run.py", line 104, in main
    sample2read_info = scripts.module.get_read_info(args['input_reads'], args['input_reads_type'])  
  File "/path/to/dir/ViWrap/scripts/module.py", line 647, in get_read_info
    fq1 = pyfastx.Fastq(metaG_reads_list[0])
SystemError: <class 'Fastq'> returned a result with an error set
```
Any idea how to solve this? the read files are ok.

Thanks
(and please say hi to Karthik from Itai)

**Comment by ChaoLab** [comment]
Hi, did you open the right of this folder "/path/to/dir/" to allow writing?
