### ISSUE TITLE
No such file or directory: 'genome_by_genome_overview.csv'

### ISSUE THREAD

**Issue by Noob-Monkey** [AnantharamanLab/ViWrap#18]
Hi,

ViWrap is a good pepeline, but I got some problems. 

How can I solve this problem?

Thanks.

Here is my command line:

```
The issued command is:
/data/yes/envs/ViWrap/important/ViWrap/ViWrap run --input_metagenome /data/yes/envs/ViWrap/important/ViWrap/example_data/test_metaG.fasta --input_reads /data/yes/envs/ViWrap/important/ViWrap/example_data/reads_1.fastq.gz,/data/yes/envs/ViWrap/important/ViWrap/example_data/reads_2.fastq.gz --out_dir metaG_ViWrap_out --db_dir /data/database/ViWrap_db2 --identify_method vb-vs --conda_env_dir /data/yes/envs/ViWrap --threads 48 --input_length_limit 2000

[2023-06-25 09:05:40] | Pre-check inputings. In processing...
[2023-06-25 09:05:40] | Looks like the input metagenome and reads, database, and custom MAGs dir (if option used) are now set up well, start up to run ViWrap pipeline
[2023-06-25 09:05:40] | Run VIBRANT-VirSorter2 method. Run VIBRANT to identify and annotate virus from input metagenome. In processing...
[2023-06-25 09:07:55] | Run VIBRANT-VirSorter2 method. Run VIBRANT to identify and annotate viruses from input metagenome. Finished
[2023-06-25 09:07:55] | Run VIBRANT-VirSorter2 method. Run VirSorter2 to identify viruses from input metagenome. Also plus CheckV to QC and trim, and KEGG, Pfam, and VOG HMMs to annotate viruses. In processing...
[2023-06-25 09:42:20] | Run VIBRANT-VirSorter2 method. Run VirSorter2 the 1st time to identify viruses from input metagenome. Finished
[2023-06-25 09:42:39] | Run VIBRANT-VirSorter2 method. Run CheckV the 1st time to QC and trim viruses identified from VirSorter2 1st run. Finished
[2023-06-25 09:52:15] | Run VIBRANT-VirSorter2 method. Run VirSorter2 the 2nd time for CheckV-trimmed sequences. Finished
[2023-06-25 09:52:28] | Run VIBRANT-VirSorter2 method. Run CheckV the 2nd time to get viral and host gene counts. Finished
[2023-06-25 09:52:55] | Run VIBRANT-VirSorter2 method. Run VIBRANT to check "keep2" and "manual_check" groups and get the final VirSorter2 virus sequences. Finished
[2023-06-25 09:52:55] | Map reads to metagenome. In processing...
Renaming metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.3.bt2.tmp to metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.3.bt2
Renaming metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.4.bt2.tmp to metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.4.bt2
Renaming metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.1.bt2.tmp to metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.1.bt2
Renaming metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.2.bt2.tmp to metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.2.bt2
Renaming metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.rev.1.bt2.tmp to metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.rev.1.bt2
Renaming metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.rev.2.bt2.tmp to metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.rev.2.bt2
[2023-06-25T01:53:15Z INFO  coverm] CoverM version 0.6.1
[2023-06-25T01:53:15Z INFO  coverm] Using min-read-percent-identity 97%
[2023-06-25T01:53:16Z INFO  coverm] CoverM version 0.6.1
[2023-06-25T01:53:16Z INFO  coverm] Setting single read percent identity threshold at 0.97 for MetaBAT adjusted coverage, and not filtering out supplementary, secondary and improper pair alignments
[2023-06-25T01:53:16Z INFO  coverm] Using min-covered-fraction 0%
[2023-06-25T01:53:16Z INFO  coverm::contig] In sample 'reads.filtered', found 172038 reads mapped out of 174248 total (98.73%)

[2023-06-25 09:53:16] | Map reads to metagenome. Finished
[2023-06-25 09:53:16] | Run vRhyme to bin viral scaffolds. In processing...
[2023-06-25 09:54:46] | Run vRhyme to bin viral scaffolds. Finished
[2023-06-25 09:54:46] | Run vContact2 to cluster viral genomes. In processing...
Traceback (most recent call last):
  File "/data/yes/envs/ViWrap/important/ViWrap/ViWrap", line 173, in <module>
    output = cli()
  File "/data/yes/envs/ViWrap/important/ViWrap/ViWrap", line 167, in cli
    args["func"](args)
  File "/data/yes/envs/ViWrap/important/ViWrap/scripts/master_run.py", line 459, in main
    scripts.module.get_genus_cluster_info(genome_by_genome_file, genus_cluster_info, ref_pro2viral_gn_map) 
  File "/data/yes/envs/ViWrap/important/ViWrap/scripts/module.py", line 335, in get_genus_cluster_info
    with open(genome_by_genome_file,"r") as file_lines:
FileNotFoundError: [Errno 2] No such file or directory: 'metaG_ViWrap_out/03_vConTACT2_outdir/genome_by_genome_overview.csv'
```

When I use vConTACT2 directly, the information is as follows:
```
/data/yes/envs/ViWrap/ViWrap-vContact2/bin/vcontact2

============================This is vConTACT2 0.9.22============================



----------------------------------Pre-Analysis----------------------------------
INFO:vcontact2: Found ClusterONE: /data/yes/envs/ViWrap/important/ViWrap/cluster_one-1.0.jar
INFO:vcontact2: Verifying clusterONE works...
INFO:vcontact2: It appears that clusterONE is functional!
INFO:vcontact2: Found Diamond: /data/yes/envs/ViWrap/bin/diamond
INFO:vcontact2: Found MCL: /usr/bin/mcxload
INFO:vcontact2: Identified 48 CPUs
INFO:vcontact2: Using reference database: ProkaryoticViralRefSeq85-ICTV
INFO:vcontact2: Using existing directory vContact_Output.


------------------------------Reference databases-------------------------------
Traceback (most recent call last):
  File "/data/yes/envs/ViWrap/ViWrap-vContact2/bin/vcontact2", line 825, in <module>
    main(options)
  File "/data/yes/envs/ViWrap/ViWrap-vContact2/bin/vcontact2", line 352, in main
    if os.path.exists(gene2genome_fp):
  File "/data/yes/envs/ViWrap/ViWrap-vContact2/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

```

**Comment by Noob-Monkey** [comment]
![微信截图_20230625115143](https://github.com/AnantharamanLab/ViWrap/assets/72112787/c083e1b7-e5ac-4a36-843d-5151ecb89cda)

**Comment by Cun-Li** [comment]
Hi, I also get this error, did you solve it?

**Comment by ChaoLab** [comment]
Can you debug the vConTACT2 env by running some test file?
Do you check the vConTACT2 issue page to find if there are any related questions and answers?

**Comment by Noob-Monkey** [comment]
thanks a lot, I rechecked the vConTACT2 according to your opinion, and I found the same issue as you submitted in Bitbucket:

"ERROR:vcontact2: Error in contig clustering
ERROR:vcontact2: No columns to parse from file"

After checking, it was found that the problem in my system came from the clusterONE. I reinstalled clusterone and put it in the system path, and modified the code of "run_vcontact2.py", removed "--c1-bin {cluster_one_jar}". Eventually the program worked successfully.

**Comment by PandengWang** [comment]
> Can you debug the vConTACT2 env by running some test file? Do you check the vConTACT2 issue page to find if there are any related questions and answers?

This bug comes from a mismatch of the ClusterOne's name. 
In the master_run.py, ClusterOne was written as `cluster_one_jar = os.path.join(args['conda_env_dir'], 'ViWrap-vContact2/bin/cluster_one-1.0.jar') `, while in `ViWrap-vContact2/bin/`, the name of ClusterOne binary file is **clusterone**！

**Comment by christinepalermo** [comment]
> > Can you debug the vConTACT2 env by running some test file? Do you check the vConTACT2 issue page to find if there are any related questions and answers?
> 
> This bug comes from a mismatch of the ClusterOne's name. In the master_run.py, ClusterOne was written as `cluster_one_jar = os.path.join(args['conda_env_dir'], 'ViWrap-vContact2/bin/cluster_one-1.0.jar') `, while in `ViWrap-vContact2/bin/`, the name of ClusterOne binary file is **clusterone**！

There's a problem with the ClusterOne file, aside from the name mismatch. Need to re-download the file into ViWrap-vContact2/bin/.

`cd path/to/ViWrap-vContact2/bin/` 
`wget -c http://www.paccanarolab.org/static_content/clusterone/cluster_one-1.0.jar`

Since this resolves the name mismatch and puts it in the correct location, there's no need to remove "--c1-bin {cluster_one_jar}" from "run_vcontact2.py".
