### ISSUE TITLE
Header issues in some cases

### ISSUE THREAD

**Issue by michoug** [AnantharamanLab/ViWrap#2]
Hi
Very nice pipeline!
I got this error while running without reads

```
Traceback (most recent call last):
  File "/work/river/Software/ViWrap/scripts/run_Tax_RefSeq.py", line 158, in <module>
    run_diamond_to_RefSeq_viral_protein_db(viwrap_outdir, vRhyme_best_bin_dir, vRhyme_unbinned_viral_gn_dir, NCBI_RefSeq_viral_protein_db_dir, pro2viral_gn_map, threads, output)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/river/Software/ViWrap/scripts/run_Tax_RefSeq.py", line 104, in run_diamond_to_RefSeq_viral_protein_db
    bin_name = pro2bin[pro]
               ~~~~~~~^^^^^
KeyError: 'Afifi_182830_3
```

While looking a bit at the code, I saw that the issue is most probably due to the fact that the header of this sequence was 

`>Afifi_182830_3        (422..589)      -1      PF01381.22      Helix-turn-helix` and not `>Afifi_182830_3` in the file `Overlap_Afifi_good/final_overlapped_virus.faa`

```
>Afifi_182830_1
MSNKPEVFDKDALKQTEXKLQEMLDNGSLDLXXDYSWSNALHSAWLQLQDTEDKNGNPVWQSCTKASVMK
>Afifi_182830_2
MSNRKKTIYVREEAEEIFDKAQQITGESLSRTIEIALRKYANDPKESVLDLANDLEVKAGLLRNRIIQEEVKDE*
>Afifi_182830_3 (422..589)      -1      PF01381.22      Helix-turn-helix
MDLDXKXRRKXLGLTQYDLAKKVGVSEVSIRKWERGITTPKPENQKKLEEVLDDE*
>Afifi_182830_4
MSDYTLFQDYDNGILGIAAGVRMKKHIIKSHDKENHTIEVEKVEEYPTKEDADEDRQELSFTDTLHESAVEKLKNIQGEVVDETGDLS*
```

It happens 8 times out of 26254.
Here are the culprits if it can help

```
>Afifi_357982_4	(2035..2355)	1	PF00085.20	Thioredoxin
>Afifi_33770_3	(1619..1786)	-1	PF01381.22	Helix-turn-helix
>Afifi_111744_12	(8543..8878)	1	PF01381.22	Helix-turn-helix
>Afifi_564869_3	(1589..1756)	-1	PF01381.22	Helix-turn-helix
>Afifi_210026_2	(564..818)	1	PF00462.24	Glutaredoxin
>Afifi_57253_2	(237..482)	1	PF00462.24	Glutaredoxin
>Afifi_182830_3	(422..589)	-1	PF01381.22	Helix-turn-helix
>Afifi_34681_6	(3791..4144)	-1	PF01381.22	Helix-turn-helix
```

Best
Greg

**Comment by ChaoLab** [comment]
Can you give me the example datasets? So that I can run them to find why it is like this on my server?

**Comment by ChaoLab** [comment]
The header issue should be solved since I have updated the "module.py" to change long headers (include "\t" in the header) into short headers (split from the first "\t", and only keep the 1st part) in the output virus faa files (within the folders of "02_vRhyme_outdir/vRhyme_best_bins_fasta_modified" and "08_ViWrap_summary_outdir/Virus_genomes_files")
