### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data4/machuang/test1/ViWrap_outdir/00_VIBRANT_test_metaG/VIBRANT_phages_test_metaG/test_metaG.phages_lytic.fna'

### ISSUE THREAD

**Issue by AndAvia** [AnantharamanLab/ViWrap#26]
hi，when i run ```
ViWrap run --input_metagenome /data4/machuang/test1/test_metaG.fasta \
           --input_reads /data4/machuang/test1/reads_1.fastq.gz,/data4/machuang/test1/reads_2.fastq.gz \
           --out_dir /data4/machuang/test1/ViWrap_outdir \
           --db_dir /data4/machuang/db/viwrap \
           --identify_method vb \
           --conda_env_dir /data4/machuang/miniconda3/envs
``` 
An error has occurred.
[2023-11-23 14:23:27] | Run VIBRANT to identify and annotate virus from input metagenome. In processing...
Traceback (most recent call last):
  File "/data4/machuang/db/ViWrap/ViWrap", line 173, in <module>
    output = cli()
  File "/data4/machuang/db/ViWrap/ViWrap", line 167, in cli
    args["func"](args)
  File "/data4/machuang/db/ViWrap/scripts/master_run.py", line 154, in main
    scripts.module.parse_vibrant_lytic_and_lysogenic_info(args['vibrant_outdir'], Path(args['input_metagenome']).stem)
  File "/data4/machuang/db/ViWrap/scripts/module.py", line 737, in parse_vibrant_lytic_and_lysogenic_info
    lytic_fasta_seq = store_seq(lytic_fasta_addr)
  File "/data4/machuang/db/ViWrap/scripts/module.py", line 28, in store_seq
    with open(input_seq_file, "r") as seq_lines:
FileNotFoundError: [Errno 2] No such file or directory: '/data4/machuang/test1/ViWrap_outdir/00_VIBRANT_test_metaG/VIBRANT_phages_test_metaG/test_metaG.phages_lytic.fna'
VIBRANT_log_run_test_metaG.log，The document shows VIBRANT error: could not identify KEGG HMM files in database directory. Please run VIBRANT_setup.py.What should I do about this error, thank you for your response.

**Comment by AndAvia** [comment]
> hi，when i run ``` ViWrap run --input_metagenome /data4/machuang/test1/test_metaG.fasta --input_reads /data4/machuang/test1/reads_1.fastq.gz,/data4/machuang/test1/reads_2.fastq.gz --out_dir /data4/machuang/test1/ViWrap_outdir --db_dir /data4/machuang/db/viwrap --identify_method vb --conda_env_dir /data4/machuang/miniconda3/envs
> 
> ```
> An error has occurred.
> [2023-11-23 14:23:27] | Run VIBRANT to identify and annotate virus from input metagenome. In processing...
> Traceback (most recent call last):
>   File "/data4/machuang/db/ViWrap/ViWrap", line 173, in <module>
>     output = cli()
>   File "/data4/machuang/db/ViWrap/ViWrap", line 167, in cli
>     args["func"](args)
>   File "/data4/machuang/db/ViWrap/scripts/master_run.py", line 154, in main
>     scripts.module.parse_vibrant_lytic_and_lysogenic_info(args['vibrant_outdir'], Path(args['input_metagenome']).stem)
>   File "/data4/machuang/db/ViWrap/scripts/module.py", line 737, in parse_vibrant_lytic_and_lysogenic_info
>     lytic_fasta_seq = store_seq(lytic_fasta_addr)
>   File "/data4/machuang/db/ViWrap/scripts/module.py", line 28, in store_seq
>     with open(input_seq_file, "r") as seq_lines:
> FileNotFoundError: [Errno 2] No such file or directory: '/data4/machuang/test1/ViWrap_outdir/00_VIBRANT_test_metaG/VIBRANT_phages_test_metaG/test_metaG.phages_lytic.fna'
> VIBRANT_log_run_test_metaG.log，The document shows VIBRANT error: could not identify KEGG HMM files in database directory. Please run VIBRANT_setup.py.What should I do about this error, thank you for your response.
> ```
#I re-ran the VIBRANT setup.
conda activate ViWrap-VIBRANT
cd ~/db/viwrap/VIBRANT_db
python VIBRANT_setup.py -test
#VIBRANT v1.2.0 is good to go!
See example_data/ for quick test files.
#再次设置数据库位置
conda activate ViWrap
ViWrap download --db_dir /data4/machuang/db/viwrap  --conda_env_dir /data4/machuang/miniconda3/envs

After that the test code was run and the same error was reported

**Comment by ChaoLab** [comment]
Maybe you were using the intermediate version when I was updating the scripts. The latest version of v1.3.0 has been released now.

**Comment by MAXzbh** [comment]
Hello, I also encountered this error after installing V-1.3.0. I would be very grateful if someone could provide a solution.

**Comment by kangluyao** [comment]
@AndAvia @MAXzbh Hi, there! Have you solved this problem? I encounter this issue with the latest version too.
