### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/isaac/proj/UTK0002/PALAVAS/PALAVAS_ViWrap/00_VIBRANT_VirSorter_PHYCOVIR_MEGAVIROME.contigs/VirSorter_PHYCOVIR_MEGAVIROME.contigs/pass/final-viral-score.tsv'

### ISSUE THREAD

**Issue by eechase** [AnantharamanLab/ViWrap#30]
Hello !

I am getting the following error when I run the pipeline. 

Traceback (most recent call last):
  File "./ViWrap", line 173, in <module>
    output = cli()
  File "./ViWrap", line 167, in cli
    args["func"](args)
  File "/lustre/isaac/proj/UTK0002/SOFTWARES/ViWrap/scripts/master_run.py", line 332, in main
    scripts.module.screen_virsorter2_result(inner_vs_outdir, keep1_list_file, keep2_list_file, discard_list_file, manual_check_list_file)
  File "/lustre/isaac/proj/UTK0002/SOFTWARES/ViWrap/scripts/module.py", line 2096, in screen_virsorter2_result
    with open(final_viral_score, 'r') as lines:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/isaac/proj/UTK0002/PALAVAS/PALAVAS_ViWrap/00_VIBRANT_VirSorter_PHYCOVIR_MEGAVIROME.contigs/VirSorter_PHYCOVIR_MEGAVIROME.contigs/pass/final-viral-score.tsv'

My input was: 

./ViWrap run --input_metagenome /lustre/isaac/proj/UTK0002/PALAVAS/PHYCOVIR_MEGAVIROME.contigs.fa --input_reads /lustre/isaac/proj/UTK0002/PALAVAS/DATA/MEGA_FOR_PALAVAS.fastq --out_dir /lustre/isaac/proj/UTK0002/PALAVAS/PALAVAS_ViWrap --db_dir /lustre/isaac/proj/UTK0002/DATABASE/ViWrap --identify_method vb-vs --conda_env_dir /lustre/isaac/proj/UTK0002/conda/envs/ViWrap --threads 20 --input_length_limit 5000

Thanks for any input you have, happy to trouble shoot however. I did not notice any specific problems with the installation etc, so not too sure.... 

Emily

**Comment by seanyao97** [comment]
Hello, I also encountered the same problem, may I ask you to solve it

**Comment by jonbakerlab** [comment]
Also having the same problem let me know if somebody figures this one out.

**Comment by seanyao97** [comment]
I have switched to using the geNomad method for predictions and have obtained satisfactory feedback on the data.

**Comment by Chuen-Lee** [comment]
I had the same issue. I solved it by installing pandas into the virsorter environment. 

micromamba activate /path/to/conda-env/ViWrap/ViWrap-vs2 
micromamba install -c anaconda pandas

micromamba and conda should work exactly the same for this purpose. Not sure if installing pandas into the ViWrap conda-env directory would work the same. Good luck!
