### ISSUE TITLE
CheckV error

### ISSUE THREAD

**Issue by tenguzame** [AnantharamanLab/ViWrap#35]
Greetings,
I was testing your pipeline on the HPC center at our facility, and I keep getting errors with CheckV:

```
[2024-02-21 07:40:18] | Pre-check inputings. In processing...
[2024-02-21 07:40:18] | Looks like the input metagenome and reads, database, and custom MAGs dir (if option used) are now set up well, start up to run ViWrap pipeline
[2024-02-21 07:40:18] | Run VIBRANT to identify and annotate viruses from input metagenome. In processing...
[2024-02-21 07:50:22] | Run VIBRANT to identify and annotate viruses from input metagenome. Finished
[2024-02-21 07:50:22] | Run vContact2 to cluster viral genomes. In processing...
[2024-02-21 09:21:20] | Run vContact2 to cluster viral genomes. Finished
[2024-02-21 09:21:20] | Run CheckV to evaluate virus genome quality. In processing...
Traceback (most recent call last):
  File "/opt/ViWrap-1.3.0/ViWrap", line 173, in <module>
    output = cli()
  File "/opt/ViWrap-1.3.0/ViWrap", line 167, in cli
    args["func"](args)
  File "/opt/ViWrap-1.3.0/scripts/master_run_wo_reads.py", line 415, in main
    scripts.module.parse_checkv_result(args['checkv_outdir'], CheckV_quality_summary)   
  File "/opt/ViWrap-1.3.0/scripts/module.py", line 487, in parse_checkv_result
    f = open(outfile, "w")
FileNotFoundError: [Errno 2] No such file or directory: '/home/mtangherlini/ERAS2/viwrap/viwrap_res/02_CheckV_outdir/CheckV_quality_summary.txt'
srun: error: falkor4: task 0: Exited with exit code 1
```

The CHECKDB variable has already been set.

**Comment by tenguzame** [comment]
To add more context to the issue, the pipelines raises the same issue both with already-identified viral genomes and with raw sequence assemblies; geNomad was used in both cases to identify viral sequences, and worked pretty fine too, so I don't think it's an issue tied with either a binning or viral identification step.

**Comment by tenguzame** [comment]
I ran again the pipeline with the example data, and the issue arises directly at the first CheckV step. It looks like CheckV is not even run by the pipeline.

**Comment by Charles-Lou** [comment]
Hello, I have encountered the same problem. Is there any solution?
