### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Host_prediction_to_genome_m90.csv'

### ISSUE THREAD

**Issue by CynthiaChibani** [AnantharamanLab/ViWrap#37]
Hey There, 
Thank you for providing a super cool pipeline.
I managed to get it to work with the recent genomad integration, but I got an error at one of the last steps of the pipeline.

My command line: 

cd $WORK/ViWrap
./ViWrap run --input_metagenome ./CB_HGUT_timeseries_ViWrap/Metagenomes_ASSEMBLY/Sport1_TP1/final_assembly.fasta \
           --input_reads ./CB_HGUT_timeseries_ViWrap/Metagenomes_READ_QC/Sport1_TP1/final_pure_reads_1.fastq.gz,./CB_HGUT_timeseries_ViWrap/Metagenomes_READ_QC/Sport1_TP1/final_pure_reads_2.fastq.gz \
           --out_dir ./CB_HGUT_timeseries_ViWrap/ViWrap_Out/Sport1_TP1_Out \
           --db_dir ./ViWrap_db/ \
           --identify_method genomad \
           --conda_env_dir $HOME/.conda/envs/ViWrap_new/ \
           --threads 12 \
           --virome \
           --input_length_limit 5000 \
           --custom_MAGs_dir ./CB_HGUT_timeseries_ViWrap/MAGs/Sport1_TP1 \
           --iPHoP_db_custom ./CB_HGUT_timeseries_ViWrap/iPHoP_db_custom/Sport1_TP1/

Error:

Traceback (most recent call last):
  File "./ViWrap", line 173, in <module>
    output = cli()
  File "./ViWrap", line 167, in cli
    args["func"](args)
  File "$WORK/ViWrap/scripts/master_run.py", line 620, in main
    scripts.module.combine_iphop_results(args, combined_host_pred_to_genome_result, combined_host_pred_to_genus_result)
  File "$WORK/ViWrap/scripts/module.py", line 1845, in combine_iphop_results
    with open(host_pred_to_genome_m90, 'r') as lines:
FileNotFoundError: [Errno 2] No such file or directory: '$WORK/CB_HGUT_timeseries_ViWrap/ViWrap_Out/Sport1_TP1_Out/07_iPHoP_outdir/Host_prediction_to_genome_m90.csv'

I would appreciate any input you might have.
Best,
Cynthia

**Comment by CynthiaChibani** [comment]
Hey there, I narrowed it down to an issue with RaFAH, perl: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory
I once solved it using the following:
cd $CONDA_PREFIX/lib
ln -s libnsl.so.3.0.0 libnsl.so.1

but it did not help in this situation, I tried to follow the issues raised [here ](https://bitbucket.org/srouxjgi/iphop/issues?q=rafah), but it does not seem I have Perl errors.

I installed iphop in a fresh micromamba env independent of ViWrap and it seems to have done the trick.

I can't figure out how to fix it in ViWrap, if you have ideas I would appreciate it :)

**Comment by BigtigerLi** [comment]
Hello brother, I want to try your command, so I would like to ask how the "--iPHoP_db_custom" parameter is used? How are the files in this path obtained or generated? Looking forward to your reply！

**Comment by ewars** [comment]
Hi.
I had a similar error. My problem was with the routes, try removing the / at the end of each route. Maybe it will help you

**Comment by XinyuGuokk** [comment]
> Hi. I had a similar error. My problem was with the routes, try removing the / at the end of each route. Maybe it will help you

Hi,
I had the same error. Could you please explain more about how to solve this problem? Thank you

**Comment by XinyuGuokk** [comment]
Hi,
I had the same error. Have you already solved this problem? If so, could you please tell me how to solve this problem?

**Comment by weipengLLL** [comment]
> Hi, I had the same error. Have you already solved this problem? If so, could you please tell me how to solve this problem?

Hi, guys.I had the same problem now. Did you fixed this? I hope you have resolved the issue. Looking forward to your good news.

**Comment by negilbert** [comment]
@CynthiaChibani Hello, I'm having this issue now. Did you end up solving it?

**Comment by susheelbhanu** [comment]
HI all, same issue here as well, the test runs seems to break, see output below

```bash
/prj/DECODE/rsn_viruses/ViWrap/ViWrap run --input_metagenome example_data/test_metaG.fasta --input_reads example_data/reads_1.fastq.gz,example_data/reads_2.fastq.gz --out_dir test_metaG_ViWrap_out --db_dir /hdd0/susbus/databases/ViWrap_db --identify_method vb-vs --conda_env_dir /prj/DECODE/conda_envs/viwrap --threads 48 --input_length_limit 5000

[2025-12-16 08:26:38] | Pre-check inputings. In processing...
[2025-12-16 08:26:40] | Looks like the input metagenome and reads, database, and custom MAGs dir (if option used) are now set up well, start up to run ViWrap pipeline
[2025-12-16 08:26:40] | Run VIBRANT-VirSorter2 method. Run VIBRANT to identify and annotate viruses from input metagenome. In processing...
[2025-12-16 08:28:42] | Run VIBRANT-VirSorter2 method. Run VIBRANT to identify and annotate viruses from input metagenome. Finished
[2025-12-16 08:28:42] | Run VIBRANT-VirSorter2 method. Run VirSorter2 to identify viruses from input metagenome. Also plus CheckV to QC and trim, and KEGG, Pfam, and VOG HMMs to annotate viruses. In processing...

[2025-12-16 09:18:56] | Run VIBRANT-VirSorter2 method. Run VirSorter2 to identify viruses from input metagenome. Finished
[2025-12-16 09:19:10] | Run VIBRANT-VirSorter2 method. Run CheckV to QC and trim viruses identified from VirSorter2. Finished
[2025-12-16 09:19:38] | Run VIBRANT-VirSorter2 method. Run VIBRANT to check "keep2" and "manual_check" groups and get the final VirSorter2 virus sequences. Finished
[2025-12-16 09:19:38] | Map reads to metagenome. In processing...
Renaming test_metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.3.bt2.tmp to test_metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.3.bt2
Renaming test_metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.4.bt2.tmp to test_metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.4.bt2
Renaming test_metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.1.bt2.tmp to test_metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.1.bt2
Renaming test_metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.2.bt2.tmp to test_metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.2.bt2
Renaming test_metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.rev.1.bt2.tmp to test_metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.rev.1.bt2
Renaming test_metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.rev.2.bt2.tmp to test_metaG_ViWrap_out/01_Mapping_result_outdir/test_metaG.bowtie2_idx.rev.2.bt2
[2025-12-16T09:19:58Z INFO  coverm] CoverM version 0.6.1
[2025-12-16T09:19:58Z INFO  coverm] Using min-read-percent-identity 97%
[2025-12-16T09:19:58Z INFO  coverm] CoverM version 0.6.1
[2025-12-16T09:19:58Z INFO  coverm] Setting single read percent identity threshold at 0.97 for MetaBAT adjusted coverage, and not filtering out supplementary, secondary and improper pair alignments
[2025-12-16T09:19:58Z INFO  coverm] Using min-covered-fraction 0%
[2025-12-16T09:19:58Z INFO  coverm::contig] In sample 'reads.filtered', found 172038 reads mapped out of 174248 total (98.73%)

[2025-12-16 09:19:59] | Map reads to metagenome. Finished
[2025-12-16 09:19:59] | Run vRhyme to bin viral scaffolds. In processing...
[2025-12-16 09:21:30] | Run vRhyme to bin viral scaffolds. Finished
[2025-12-16 09:21:30] | Run vContact2 to cluster viral genomes. In processing...
[2025-12-16 10:40:12] | Run vContact2 to cluster viral genomes. Finished
[2025-12-16 10:40:12] | Run CheckV to evaluate virus genome quality. In processing...
[2025-12-16 10:42:32] | Run CheckV to evaluate virus genome quality. Finished
[2025-12-16 10:42:32] | Run dRep to cluster virus species. In processing...
[2025-12-16 10:43:02] | Run dRep to cluster virus species. Finished
[2025-12-16 10:43:02] | Conduct taxonomic charaterization. In processing...
[2025-12-16 10:44:26] | Conduct taxonomic charaterization. Finished
[2025-12-16 10:44:26] | Conduct Host prediction by iPHoP. In processing...
[2025-12-16 10:46:31] | Conduct Host prediction by iPHoP. Finished
[2025-12-16 10:46:31] | Get virus genome abundance. Finished
Traceback (most recent call last):
  File "/prj/DECODE/rsn_viruses/ViWrap/ViWrap", line 173, in <module>
    output = cli()
  File "/prj/DECODE/rsn_viruses/ViWrap/ViWrap", line 167, in cli
    args["func"](args)
  File "/prj/DECODE/rsn_viruses/ViWrap/scripts/master_run.py", line 653, in main
    scripts.module.combine_iphop_results(args, combined_host_pred_to_genome_result, combined_host_pred_to_genus_result)
  File "/prj/DECODE/rsn_viruses/ViWrap/scripts/module.py", line 1883, in combine_iphop_results
    with open(host_pred_to_genome_m90, 'r') as lines:
FileNotFoundError: [Errno 2] No such file or directory: 'test_metaG_ViWrap_out/07_iPHoP_outdir/Host_prediction_to_genome_m90.csv'
```

Any input would be appreciated. 

Best,
Susheel
