### ISSUE TITLE
Problem after the step "[2023-02-09 15:16:41] | Get virus genome abundance. Finished"

### ISSUE THREAD

**Issue by rdenise** [AnantharamanLab/ViWrap#4]
## Problem Description
ViWrap 1.2.1 is encountering an error while running the command 

```bash
ViWrap/ViWrap run --input_metagenome ZSM005_contigs.filtered.sorted.fasta --input_reads ZSM005_1.fastq.gz,ZSM005_2.fastq.gz --out_dir ./ViWrap_output_vb_vs --db_dir ViWrap_db --identify_method vb-vs --conda_env_dir miniconda3/envs/ViWrap --threads 20 --input_length_limit 2000
```

The error occurs after the "Get virus genome abundance" step has finished.

## Error Message

```python
Traceback (most recent call last):
  File "ViWrap/ViWrap", line 172, in <module>
    output = cli()
  File "ViWrap/ViWrap", line 166, in cli
    args["func"](args)
  File "ViWrap/scripts/master_run.py", line 597, in main
    scripts.module.get_virus_genome_abundance(args)
  File "ViWrap/scripts/module.py", line 913, in get_virus_genome_abundance
    virus_abundance = get_abundance(final_virus_genomes_dir, virus_fastq_dir, args)
  File "ViWrap/scripts/module.py", line 848, in get_abundance
    virus_abundance = virsorter_abundance.run(args, virus_abundance)
  File "ViWrap/scripts/module/virsorter_abundance.py", line 179, in run
    virus_abundance = abundance.run(args, virus_abundance)
  File "ViWrap/scripts/module/abundance.py", line 147, in run
    report_df.to_csv(report_path, index=False)
  File "miniconda3/envs/ViWrap/lib/python3.7/site-packages/pandas/core/frame.py", line 1767, in to_csv
    formatter.save()
  File "miniconda3/envs/ViWrap/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 189, in save
    self._save()
  File "miniconda3/envs/ViWrap/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 193, in _save
    writer.write(self.data)
  File "miniconda3/envs/ViWrap/lib/python3
```

**Comment by ChaoLab** [comment]
It looks like something is wrong with the pandas. Can you use python=3.8 to set up your ViWrap conda env?
