### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: *.phages_lytic.fna

### ISSUE THREAD

**Issue by clementcoclet** [AnantharamanLab/ViWrap#40]
Hi,

I am trying to run ViWrap using the command:

ViWrap run -i MVP_PAPER_LOXAHATCHEE/00_ASSEMBLIES/Ga0436458_contigs.fasta -r MVP_PAPER_LOXAHATCHEE/00_READ_FILES/52391.3.317024.CGGAATAC-GTATTCCG.filter-METAGENOME_R1.fastq,MVP_PAPER_LOXAHATCHEE/00_READ_FILES/52391.3.317024.CGGAATAC-GTATTCCG.filter-METAGENOME_R2.fastq --out_dir MVP_PAPER_LOXAHATCHEE/VIBRANT_ANALYSIS/ViWrap_Output_3300038401 --db_dir ViWrap/VIWRAP_DATABASES/ --identify_method vb-vs-dvf --conda_env_dir ViWrap/ --threads 30 --input_length_limit 5000

It returns this error: `### Welcome to ViWrap ###

The issued command is:
/clusterfs/jgi/groups/science/homes/ccoclet/scratch/ViWrap/ViWrap run --input_metagenome MVP_PAPER_LOXAHATCHEE/00_ASSEMBLIES/Ga0436458_contigs.fasta --input_reads MVP_PAPER_LOXAHATCHEE/00_READ_FILES/52391.3.317024.CGGAATAC-GTATTCCG.filter-METAGENOME_R1.fastq,MVP_PAPER_LOXAHATCHEE/00_READ_FILES/52391.3.317024.CGGAATAC-GTATTCCG.filter-METAGENOME_R2.fastq --out_dir MVP_PAPER_LOXAHATCHEE/VIBRANT_ANALYSIS/ViWrap_Output_3300038401 --db_dir ViWrap/VIWRAP_DATABASES/ --identify_method vb-vs-dvf --conda_env_dir ViWrap/ --threads 30 --input_length_limit 5000

[2024-03-29 10:35:09] | Pre-check inputings. In processing...
[2024-03-29 10:43:51] | Looks like the input metagenome and reads, database, and custom MAGs dir (if option used) are now set up well, start up to run ViWrap pipeline
[2024-03-29 10:43:51] | Run VIBRANT-VirSorter2-DVF method. Run VIBRANT to identify and annotate viruses from input metagenome. In processing...
Traceback (most recent call last):
File "/clusterfs/jgi/groups/science/homes/ccoclet/scratch/ViWrap/ViWrap", line 173, in
output = cli()
File "/clusterfs/jgi/groups/science/homes/ccoclet/scratch/ViWrap/ViWrap", line 167, in cli
args["func"](https://github.com/AnantharamanLab/ViWrap/issues/args)
File "/clusterfs/jgi/scratch/science/metagen/ccoclet/ViWrap/scripts/master_run.py", line 236, in main
scripts.module.parse_vibrant_lytic_and_lysogenic_info(inner_vb_outdir, Path(args['input_metagenome']).stem)
File "/clusterfs/jgi/scratch/science/metagen/ccoclet/ViWrap/scripts/module.py", line 919, in parse_vibrant_lytic_and_lysogenic_info
lytic_fasta_seq = store_seq(lytic_fasta_addr)
File "/clusterfs/jgi/scratch/science/metagen/ccoclet/ViWrap/scripts/module.py", line 28, in store_seq
with open(input_seq_file, "r") as seq_lines:
FileNotFoundError: [Errno 2] No such file or directory: 'MVP_PAPER_LOXAHATCHEE/VIBRANT_ANALYSIS/ViWrap_Output_3300038401/00_VIBRANT_VirSorter_DeepVirFinder_Ga0436458_contigs/VIBRANT_Ga0436458_contigs/VIBRANT_phages_Ga0436458_contigs/Ga0436458_contigs.phages_lytic.fna'`

Any help, please.
Best,
Clement

**Comment by ewars** [comment]
Hi.
I had the same error. The problem was with the paths, try removing the / at the end of each route. 

--db_dir ViWrap/VIWRAP_DATABASES --identify_method vb-vs-dvf --conda_env_dir ViWrap
