### ISSUE TITLE
VS2 issue

### ISSUE THREAD

**Issue by drob2727** [AnantharamanLab/ViWrap#52]
ViWrap run --input_metagenome /home/fslcollab273/nobackup/archive/SALSA_Assembly/SALSA_ASSEMBLY/final_assembly.fasta \
           --input_reads /home/fslcollab273/nobackup/archive/SALSA_Assembly/ALL_SLM_SLM_BON_QC_READS/SLMCELL_1.fastq,/home/fslcollab273/nobackup/archive/SALSA_Assembly/ALL_SLM_SLM_BON_QC_READS/SLMCELL_2.fastq \
           --out_dir ./ViWrapTest_DR \
           --db_dir /home/fslcollab273/fsl_groups/grp_metawrap/nobackup/archive/ViWrap_DR/ViWrap_db \
           --identify_method vs \
           --conda_env_dir /home/fslcollab273/.conda/envs \
           --threads 128 \
           --virome \
           --input_length_limit 5000
### Welcome to ViWrap ###

The issued command is:
/home/fslcollab273/fsl_groups/grp_metawrap/nobackup/archive/ViWrap_DR/ViWrap-1.3.0/ViWrap run --input_metagenome /home/fslcollab273/nobackup/archive/SALSA_Assembly/SALSA_ASSEMBLY/final_assembly.fasta --input_reads /home/fslcollab273/nobackup/archive/SALSA_Assembly/ALL_SLM_SLM_BON_QC_READS/SLMCELL_1.fastq,/home/fslcollab273/nobackup/archive/SALSA_Assembly/ALL_SLM_SLM_BON_QC_READS/SLMCELL_2.fastq --out_dir ./ViWrapTest_DR --db_dir /home/fslcollab273/fsl_groups/grp_metawrap/nobackup/archive/ViWrap_DR/ViWrap_db --identify_method vs --conda_env_dir /home/fslcollab273/.conda/envs --threads 128 --virome --input_length_limit 5000

[2024-09-19 20:03:39] | Pre-check inputings. In processing...
[2024-09-19 20:08:40] | Looks like the input metagenome and reads, database, and custom MAGs dir (if option used) are now set up well, start up to run ViWrap pipeline
[2024-09-19 20:08:40] | Run VirSorter2 to identify viruses from input metagenome. Also plus CheckV to QC and trim, and KEGG, Pfam, and VOG HMMs to annotate viruses. In processing...
[2024-09-19 20:09:39] | Run VirSorter2 to identify viruses from input metagenome. Finished
[2024-09-19 20:09:41] | Run CheckV to QC and trim viruses identified from VirSorter2. Finished
Traceback (most recent call last):
  File "/home/fslcollab273/fsl_groups/grp_metawrap/nobackup/archive/ViWrap_DR/ViWrap-1.3.0/ViWrap", line 173, in <module>
    output = cli()
  File "/home/fslcollab273/fsl_groups/grp_metawrap/nobackup/archive/ViWrap_DR/ViWrap-1.3.0/ViWrap", line 167, in cli
    args["func"](args)
  File "/nobackup/archive/grp/grp_metawrap/ViWrap_DR/ViWrap-1.3.0/scripts/master_run.py", line 179, in main
    scripts.module.screen_virsorter2_result(args['virsorter_outdir'], keep1_list_file, keep2_list_file, discard_list_file, manual_check_list_file)
  File "/nobackup/archive/grp/grp_metawrap/ViWrap_DR/ViWrap-1.3.0/scripts/module.py", line 2096, in screen_virsorter2_result
    with open(final_viral_score, 'r') as lines:
FileNotFoundError: [Errno 2] No such file or directory: './ViWrapTest_DR/00_VirSorter_final_assembly/pass/final-viral-score.tsv'

**Comment by Drob84761** [comment]
Why would VS2 be running through the assembly in 1 minute? I installed everything according to the instructions and had no issues but running the software is not working. I have previously ran VS2 on this assembly and got 1200 viromes over 5000 bp. I used this one to test because my other dataset was getting the same issue. I am running this on a sbatch script if that helps.

**Comment by yyyangzd** [comment]
Did you solve the problem? I have the same problem too.

**Comment by Drob84761** [comment]
No I haven't yet. Ive been working on it for days. I think the issue is with the master set up script. My conda environments are so much smaller than what they are supposed to be. I have ran the set-up with every variation I can think of. Im out of ideas.

**Comment by brilliant2643** [comment]
> You can check if there is a yaml file and the corresponding conda environment in the conda_env file under the vs section in your database. This issue troubled me for a long time, until I discovered that the size of my database download was incorrect, and the conda environment was missing.

Hi! I have the same problem when running viwrap with all the identify method, I manually install all the environments with yaml files and all the databases for the environments. How can I check if I download and set up the environments and databases correctly? Thanks a lot!

**Comment by try-hunter** [comment]
> > You can check if there is a yaml file and the corresponding conda environment in the conda_env file under the vs section in your database. This issue troubled me for a long time, until I discovered that the size of my database download was incorrect, and the conda environment was missing.
> 
> Hi! I have the same problem when running viwrap with all the identify method, I manually install all the environments with yaml files and all the databases for the environments. How can I check if I download and set up the environments and databases correctly? Thanks a lot!

You can use `conda env list `to check whether the conda environment was successfully installed. As for the database, since the author didn't provide MD5 checksums for verification, you can try using the` du `command to check the storage size of each database and see if it roughly matches the size provided by the author.

**Comment by brilliant2643** [comment]
> > > You can check if there is a yaml file and the corresponding conda environment in the conda_env file under the vs section in your database. This issue troubled me for a long time, until I discovered that the size of my database download was incorrect, and the conda environment was missing.
> > 
> > 
> > Hi! I have the same problem when running viwrap with all the identify method, I manually install all the environments with yaml files and all the databases for the environments. How can I check if I download and set up the environments and databases correctly? Thanks a lot!
> 
> You can use `conda env list `to check whether the conda environment was successfully installed. As for the database, since the author didn't provide MD5 checksums for verification, you can try using the`du`command to check the storage size of each database and see if it roughly matches the size provided by the author.

Thanks for your reply! I tried `conda env list` command, and found all the environments were successfully installed, still when I run the command, I got errors. As for the `du` command, I tried and found the size of databases and environments path are all larger or smaller than the one listed in README file. I'm so confused.
