### ISSUE TITLE
Problem with iPHoP step

### ISSUE THREAD

**Issue by BenMinch** [AnantharamanLab/ViWrap#7]
Hello, I have been running into a problem with the iPHoP step of the program as this is the output I am receiving.

`FileNotFoundError: [Errno 2] No such file or directory: './ViWrap_S2/07_iPHoP_outdir/Host_prediction_to_genome_m90.csv'`

I believe it is an error with rafah as when I looked into the rafah.log file, I found this error as well:

`No such file or directory at /home/benjamin/Desktop/ViWrap/ViWrap-iPHoP/lib/python3.8/site-packages/iphop/utils/RaFAH_v0.3.pl line 313`

I looked at this location and that file seems to be there, so I don't know what the problem is. Is there anyway to fix this, or to bypass using rafah. The main reason this error stinks is that it is preventing the entire virus statistics and visualization folder from being generated, which I want for my analysis. 

Hope you can help, thanks!

**Comment by ChaoLab** [comment]
Hi, in the lastest version of ViWrap (v1.2.1), we used "python=3.8 iphop=1.2.0" to install the iPHoP conda env. Maybe, the easiest way to deal with this is that you will need to check the iPHoP conda env and db whether they both meet the requirements. If not, you can re-install the conda env and db to make a new test. We can deal with our test datasets well with the current iPHoP conda env and db on our server. I guess it is an environment issue instead of a coding issue within the RaFAH script. Best!

**Comment by BenMinch** [comment]
Both my python and iphop versions are the same as you have described above. I am working on an ubuntu computer. It still is not working.

**Comment by ChaoLab** [comment]
I am also testing and using ViWrap on a Ubuntu server. So that will not be an issue. Can you make a test to see if your iPHoP conda env and db have been properly installed by using the test datasets and following the instructions provided by iPHoP (https://bitbucket.org/srouxjgi/iphop/src/main/)?

**Comment by BenMinch** [comment]
I followed the instructions and ran iPHoP separately with your test datasets, but it still failed. This time on the aggregation of data step, giving this error : `ValueError: For argument "ascending" expected type bool, received type str`

**Comment by BenMinch** [comment]
I figured it out. It was a problem with the iphop script in the environment called databaseprep_rf.py. It had a call for ascending and was using "False" instead of False without quotation marks. I removed them and it all worked good.

**Comment by qazwsx1995** [comment]
> 



> I figured it out. It was a problem with the iphop script in the environment called databaseprep_rf.py. It had a call for ascending and was using "False" instead of False without quotation marks. I removed them and it all worked good.

Sorry, after I created the environment, where should I find this python script and modify it?

**Comment by qazwsx1995** [comment]
> I figured it out. It was a problem with the iphop script in the environment called databaseprep_rf.py. It had a call for ascending and was using "False" instead of False without quotation marks. I removed them and it all worked good. 
Sorry to bother you, can you tell me exactly where to modify the script? @BenMinch

**Comment by BenMinch** [comment]
Yea, for sure. Mine was located here `home/user/Desktop/ViWrap/ViWrap-iPHoP/lib/python3.8/site-packages/iphop/modules/dataprep_rf.py`. The " ViWrap-iPHoP" folder is wherever you downloaded that virtual environment. The ascending erro is on line 148 of that dataprep_rf.py file. Hope this helps @qazwsx1995 .

**Comment by qazwsx1995** [comment]
Sorry to bother you again, can you tell me in detail how to modify that script? I still have this error when I run it now @BenMinch

**Comment by BenMinch** [comment]
In line 148 there is a a modifier called 'ascending' that looks like this `ascending=["False","False","False"]`. I changed it to `ascending=[False,False,False]`.

**Comment by XiaomengWang0413** [comment]
https://github.com/AnantharamanLab/ViWrap/issues/7#issue-1592427944
 Hi BenMicnch ,I encountered the same problem, but I modified it according to your method, and still got an error.@BenMinch
best

**Comment by XiaomengWang0413** [comment]
Hello, I encountered the same problem and modified it according to your method, but a similar error also appeared.

Traceback (most recent call last):
  File "./ViWrap", line 172, in <module>
    output = cli()
  File "./ViWrap", line 166, in cli
    args["func"](args)
  File "/data/home/xiaomeng/software/ViWrap/scripts/master_run.py", line 598, in main
    scripts.module.combine_iphop_results(args, combined_host_pred_to_genome_result, combined_host_pred_to_genus_result)
  File "/data/home/xiaomeng/software/ViWrap/scripts/module.py", line 1363, in combine_iphop_results
    with open(host_pred_to_genome_m90, 'r') as lines:
FileNotFoundError: [Errno 2] No such file or directory: './ViWrap_outdir2/07_iPHoP_outdir/Host_prediction_to_genome_m90.csv'

**Comment by Rap0ss0** [comment]
Hi guys i'm having problem with iPHOP too, I already changed the line 148 to ascending=[False,False,False] but the problem persists. All the others steps before iPHOP are finished right but iPHOP shows as finished however his folder is empety. When I run iPHOP alone it's fuctions fine and deliver the results. Anyone know what to do to solve this problem??


[2024-12-07 07:00:17] | Conduct Host prediction by iPHoP. In processing...
[2024-12-07 07:00:39] | Conduct Host prediction by iPHoP. Finished
[2024-12-07 07:00:39] | Get virus genome abundance. Finished
Traceback (most recent call last):
  File "/home/labmicro/ViWrap/ViWrap", line 173, in <module>
    output = cli()
  File "/home/labmicro/ViWrap/ViWrap", line 167, in cli
    args["func"](args)
  File "/home/labmicro/ViWrap/scripts/master_run.py", line 620, in main
    scripts.module.combine_iphop_results(args, combined_host_pred_to_genome_result, combined_host_pred_to_genus_result)
  File "/home/labmicro/ViWrap/scripts/module.py", line 1845, in combine_iphop_results
    with open(host_pred_to_genome_m90, 'r') as lines:
FileNotFoundError: [Errno 2] No such file or directory: '/data/labmicro/caio/viwrap/test/07_iPHoP_outdir/Host_prediction_to_genome_m90.csv'
