### ISSUE TITLE
Vcontact2 error

### ISSUE THREAD

**Issue by CynthiaChibani** [AnantharamanLab/ViWrap#8]
Thanks for the very nice pipeline. 
I tried to use it on a sample I have and I come across an error with vcontact2:

Traceback (most recent call last):
  File "./ViWrap", line 172, in <module>
    output = cli()
  File "./ViWrap", line 166, in cli
    args["func"](args)
  File "/work_beegfs/sunam088/ViWrap/scripts/master_run.py", line 459, in main
    scripts.module.get_genus_cluster_info(genome_by_genome_file, genus_cluster_info, ref_pro2viral_gn_map) 
  File "/work_beegfs/sunam088/ViWrap/scripts/module.py", line 335, in get_genus_cluster_info
    with open(genome_by_genome_file,"r") as file_lines:
FileNotFoundError: [Errno 2] No such file or directory: '/work_beegfs/sunam088/ViWrap/S1_Out/03_vConTACT2_outdir/genome_by_genome_overview.cs

Would appreciate your help.

and would you consider adding an option --continue when something fails?

**Comment by CynthiaChibani** [comment]
I ran vcontact2 separately and added the folder in the output folder structure. seems to have fixed the problem :)
